[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:gunicorn]
command=gunicorn resume_analyzer.wsgi:application --bind 0.0.0.0:%(ENV_PORT)s --workers 2 --threads 4 --timeout 120
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autostart=true
autorestart=true
