# Generated by Django 5.1.15 on 2026-06-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ResumeAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("filename", models.CharField(max_length=255)),
                ("job_desc_snippet", models.CharField(blank=True, max_length=200)),
                ("match_score", models.IntegerField(default=0)),
                ("matched_skills", models.JSONField(default=list)),
                ("missing_skills", models.JSONField(default=list)),
                ("experience_gaps", models.JSONField(default=list)),
                ("suggestions", models.JSONField(default=list)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
