# Generated by Django 5.1.15 on 2026-06-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumeanalysis",
            name="upskill_paths",
            field=models.JSONField(default=list),
        ),
    ]
