# Generated by Django 5.1.15 on 2026-06-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_resumeanalysis_upskill_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='ats_format_issues',
            field=models.JSONField(default=list),
        ),
    ]
