# Generated by Django 5.1.15 on 2026-06-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_resumeanalysis_ats_format_issues'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='impact_critiques',
            field=models.JSONField(default=list),
        ),
    ]
