# Generated by Django 5.1.15 on 2026-06-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0006_alter_resumeanalysis_cover_letter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumeanalysis",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
    ]
