# Generated by Django 5.1.15 on 2026-06-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0007_resumeanalysis_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumeanalysis",
            name="interview_questions",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
