# Generated by Django 5.1.15 on 2026-06-17 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0010_userprofile_current_period_end_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="stripe_customer_id",
            new_name="razorpay_customer_id",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="stripe_subscription_id",
            new_name="razorpay_subscription_id",
        ),
    ]
