# Generated by Django 5.1.15 on 2026-06-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0011_rename_stripe_customer_id_userprofile_razorpay_customer_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumeanalysis",
            name="searchability_checks",
            field=models.JSONField(default=list),
        ),
    ]
