# Generated by Django 5.1.15 on 2026-06-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0012_resumeanalysis_searchability_checks"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumeanalysis",
            name="completion_tokens",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="prompt_tokens",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
