# Generated by Django 5.1.15 on 2026-06-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0013_resumeanalysis_completion_tokens_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("discount_percent", models.IntegerField(help_text="Discount percentage (0-100)")),
                (
                    "max_uses",
                    models.IntegerField(
                        default=100, help_text="Maximum number of times this coupon can be used"
                    ),
                ),
                (
                    "uses",
                    models.IntegerField(
                        default=0, help_text="Number of times this coupon has been used"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
