# Generated by Django 5.1.15 on 2026-06-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0014_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="has_used_free_trial",
            field=models.BooleanField(default=False),
        ),
    ]
