# Generated by Django 5.1.15 on 2026-06-21 01:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0015_userprofile_has_used_free_trial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumeanalysis",
            name="slug",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
