# Generated by Django 5.1.15 on 2026-06-21 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0016_resumeanalysis_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumeanalysis",
            name="category",
            field=models.CharField(default="Other", max_length=100),
        ),
    ]
