# Generated by Django 5.1.15 on 2026-06-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0017_resumeanalysis_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
