# Generated by Django 5.1.15 on 2026-06-22 19:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0020_resumeanalysis_structured_resume_interviewsession_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalizedResume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("language", models.CharField(max_length=50)),
                ("target_market", models.CharField(max_length=100)),
                ("translated_resume", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="localizations",
                        to="analyzer.resumeanalysis",
                    ),
                ),
            ],
        ),
    ]
