# Generated by Django 5.1.15 on 2026-06-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0021_localizedresume"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreWrittenBullet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("job_role", models.CharField(db_index=True, max_length=150)),
                ("category", models.CharField(max_length=100)),
                ("bullet_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
