# Generated by Django 5.1.15 on 2026-06-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0022_prewrittenbullet"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumeanalysis",
            name="fraud_audit",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
