# Generated by Django 5.1.15 on 2026-06-26 06:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0023_resumeanalysis_fraud_audit"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "summary",
                    models.TextField(help_text="A short summary of the post shown in list cards."),
                ),
                ("content", models.TextField(help_text="HTML content of the blog post.")),
                (
                    "read_time",
                    models.IntegerField(default=5, help_text="Estimated reading time in minutes."),
                ),
                ("category", models.CharField(default="Career Advice", max_length=100)),
                (
                    "cover_image",
                    models.URLField(
                        blank=True, help_text="Optional URL of the cover image.", max_length=500
                    ),
                ),
                ("published_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
    ]
