# Generated by Django 5.1.15 on 2026-06-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0029_add_blog_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumeanalysis",
            name="areas_for_growth",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="competency_matrix",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="experience_trajectory",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="formatting_readability",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="key_strengths",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="onboarding_checklist",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="project_portfolio_ideas",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="salary_benchmark",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
