# Generated by Django 5.1.15 on 2026-06-29 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0030_resumeanalysis_areas_for_growth_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewsession",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interview_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
